version: "3.7"

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      network: host
    image: angular
    container_name: 7w-front
    #command: ["sleep","infinity"]
    ports:
     - 4200:4200
    volumes:
     - ./:/app/
    networks:
      - 7w-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      network: host
    image: node
    container_name: 7w-backend
    #command: ["sleep","infinity"]
    command: ["npm", "run", "dev"]
    ports:
      - 7000:7000
    environment:
      MYSQL_HOST: db
      MYSQL_USERNAME: 7wonders
      MYSQL_PASSWORD: 7wonders
      MYSQL_DB: 7wonders
      PORT: 7000
      COOKIE_SECRET: secret
      SECRET_KEY: secretkey

    volumes:
      - ./backend:/usr/src/app/
    networks:
      - 7w-network
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: 7wonders
      MYSQL_USER: 7wonders
      MYSQL_PASSWORD: 7wonders
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - 7w-network


networks:
  7w-network:
    driver: bridge